# Generated by Django 2.2 on 2019-05-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('playlist_img', models.ImageField(upload_to='img/playlist_cover/')),
            ],
            options={
                'verbose_name': 'playlist',
                'ordering': ['update_date'],
            },
        ),
        migrations.CreateModel(
            name='Song_is_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'song_is_in',
            },
        ),
    ]
