# Generated by Django 2.2 on 2019-05-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('album', '0002_auto_20190509_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('playlist_img', models.ImageField(upload_to='img/playlist_cover/')),
                ('contains', models.ManyToManyField(to='album.Song')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': 'playlist',
                'ordering': ['update_date'],
            },
        ),
    ]
