# Generated by Django 2.2 on 2019-05-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song_is_in',
            options={'ordering': ['id_playlist', 'id_song'], 'verbose_name': 'song_is_in'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='contains',
            field=models.ManyToManyField(related_name='in_playlists', to='album.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='saved_by',
            field=models.ManyToManyField(related_name='playlists_created', to='user.User'),
        ),
        migrations.AddField(
            model_name='song_is_in',
            name='id_playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='song_is_in',
            name='id_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.Song'),
        ),
    ]
