# Generated by Django 2.2 on 2019-05-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190512_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='saved_by',
        ),
    ]
