# Generated by Django 2.2 on 2019-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20190516_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_img',
            field=models.ImageField(default='img/playlist_cover/no_image.png', upload_to='img/playlist_cover/'),
        ),
    ]
