# Generated by Django 2.2 on 2019-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='img/')),
                ('following', models.ManyToManyField(to='user.User')),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
    ]
