# Generated by Django 2.2 on 2019-05-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190512_0200'),
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening_session',
            name='fk_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.Song'),
        ),
        migrations.AddField(
            model_name='listening_session',
            name='fk_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_artist',
            field=models.ManyToManyField(related_name='followers', to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_user',
            field=models.ManyToManyField(to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_album',
            field=models.ManyToManyField(related_name='saved_by', to='album.Album'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(related_name='savers', to='playlist.Playlist'),
        ),
    ]
