# Generated by Django 2.2 on 2019-05-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('album', '0002_auto_20190509_2133'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id_user'], 'verbose_name': 'user'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='following_user',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(to='playlist.Playlist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='img/user_avatar/'),
        ),
        migrations.CreateModel(
            name='Listening_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fk_song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.Song')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
            options={
                'verbose_name': 'listening',
                'ordering': ['date'],
            },
        ),
    ]
