# Generated by Django 2.2 on 2019-05-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190512_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(related_name='playlists', to='playlist.Playlist'),
        ),
    ]
