# Generated by Django 2.2 on 2019-05-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190512_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(related_name='savers', to='playlist.Playlist'),
        ),
    ]
