# Generated by Django 2.2 on 2019-05-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['album_key', 'out_date'], 'verbose_name': 'song'},
        ),
        migrations.AddField(
            model_name='album',
            name='artist_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.Album'),
        ),
    ]
