# Generated by Django 2.2.1 on 2019-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20190518_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_img',
            field=models.ImageField(upload_to='media/img/album_cover/'),
        ),
    ]
