# Generated by Django 2.2 on 2019-05-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('out_date', models.DateField(auto_now_add=True)),
                ('album_img', models.ImageField(upload_to='img/album_cover/')),
            ],
            options={
                'verbose_name': 'album',
                'ordering': ['out_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_song', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=5)),
                ('out_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='songs/')),
                ('features', models.ManyToManyField(related_name='appears_in', to='artist.Artist')),
            ],
            options={
                'verbose_name': 'song',
            },
        ),
    ]
