# Generated by Django 2.2 on 2019-05-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='saved_by',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
