# Generated by Django 2.2 on 2019-05-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20190515_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_artist', to='artist.Artist'),
        ),
    ]
