# Generated by Django 2.2 on 2019-05-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20190518_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_key',
            new_name='main_artist',
        ),
    ]
