# Generated by Django 2.2 on 2019-05-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20190518_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='features',
            new_name='artist_featured',
        ),
    ]
