# Generated by Django 2.2 on 2019-05-15 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20190515_0404'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening_session',
            name='fk_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.Song'),
        ),
        migrations.AddField(
            model_name='listening_session',
            name='fk_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
