# Generated by Django 2.2 on 2019-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following_artist',
            field=models.ManyToManyField(related_name='follower', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_playlist',
            field=models.ManyToManyField(related_name='saver', to='playlist.Playlist'),
        ),
    ]
