# Generated by Django 2.2 on 2019-05-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='img/artist_photo/')),
                ('appears_in', models.ManyToManyField(to='album.Song')),
                ('followed_by', models.ManyToManyField(to='user.User')),
            ],
            options={
                'verbose_name': 'artist',
                'ordering': ['id_artist'],
            },
        ),
    ]
