# Generated by Django 2.2 on 2019-05-15 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0002_auto_20190515_0404'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song_is_in',
            options={'ordering': ['id_playlist', 'id_song'], 'verbose_name': 'song_is_in'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song_is_in',
            name='id_playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='song_is_in',
            name='id_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.Song'),
        ),
    ]
