# Generated by Django 2.2 on 2019-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190515_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/playlist_cover/'),
        ),
    ]
