# Generated by Django 2.2 on 2019-05-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20190516_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
