# Generated by Django 2.2.1 on 2019-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_remove_playlist_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/playlist_cover/'),
        ),
    ]
